### ISSUE TITLE
feature request: use as operator

### ISSUE THREAD

**Issue by thisguychris** [blackCauldron7/surround.nvim#3]
While operating in visual mode works most of the time I use `vim-surround` in operator mode. `yssb` would surround the whole line with`)` for example.

And I think a lot of advanced vim users actually prefer operator mode than visually selecting first before applying a command.

Anyway, thanks for making this plugin. I'm looking forward to your progress.

**Comment by blackCauldron7** [comment]
I tried to do that first but I really don't know how to achieve that functionality. I need help to do this.

**Comment by thisguychris** [comment]
Okay, copy. Perhaps exposing a function for surround first? And maybe we can get away with simple vim bindings using omap?

**Comment by blackCauldron7** [comment]
the only special one is yss right? for whole line others are inbuilt to vim like iw, W iirc? @thisguychris

**Comment by blackCauldron7** [comment]
Latest commit adds this feature.

**Comment by Maswor** [comment]
Hello @blackCauldron7 , could you please support visual mode. My `timeoutlen` is 500 ms, which is proper for `which-key`. But for `surround.nvim` I never be able to quickly type `sr("` for example. It would be great if I can select a text, `srb"` (replace the block with a double quote). Where block will match [], {}, '' ...etc.

**Comment by blackCauldron7** [comment]
@Maswor can you provide an example. I am having trouble understanding your use case.

**Comment by Maswor** [comment]
Thank you for reopening the issues. Let say I have these texts:

```ts
ctx.currentData(new DataID("~/Desktop/dataID.json"))
```

I want to change the first `()` into `[]` such that it looks like:

```ts
ctx.currentData[new DataID("~/Desktop/data.json")]
```

If my cursor is within `"~/Desktop/data.json"`, `sr([` will not modify the outer bracket and it's hard to move the cursor say `DataID` then type `sr([` quickly.

It would be great if I can use `coc.nvim` to incrementally select `(new DataID("~/Desktop/dataID.json"))` then type `srb[`. The `b` will match the first `()` and turn it into `[]`.

Further, when I type the sequence `srb[`, it will turn into an operator in a way that `srb` will wait for me to think of the surround I want (operator mode). It mostly means I can take time to find the `[` key in the keyboard to type.

This is similar to how `machakann/vim-sandwich` works. I love your plugins for quickly turn `'`` into `""` for example, since I can largely stay in `Normal` mode. But there are cases when the selection text is quite complex, spanning multiple lines, and comes from other plugins (i.e. `coc.nvim`, `nvim-treesitter`). These cases I would love to have operator mode!

**Comment by blackCauldron7** [comment]
> It would be great if I can use coc.nvim to incrementally select (new DataID("~/Desktop/dataID.json")) then type srb[. The b will match the first () and turn it into [].

I think a count would be better for this use case  For e.g. `sr2b[`
What do you think?

And as for the operator mode i'll look into it.

**Comment by blackCauldron7** [comment]
latest commit adds a count option please close the issue if it fixes your use case

**Comment by Maswor** [comment]
Hello, thank you. You could close the issue now, I'm not the original poster and couldn't close it myself!
