### ISSUE TITLE
Add support to vim-repeat

### ISSUE THREAD

**Issue by augustocdias** [blackCauldron7/surround.nvim#39]
Is it possible to add support for [vim-repeat](https://github.com/tpope/vim-repeat)?

From their docs it seems straightforward:

> Adding support to a plugin is generally as simple as the following command at the end of your map functions.

```
silent! call repeat#set("\<Plug>MyWonderfulMap", v:count)
```

**Comment by blackCauldron7** [comment]
I believe its not that simple the current implementation of the plugins is really ugly.

**Comment by Daxtorim** [comment]
The problem with vim-repeat is that it expects that special snippet at the *very end* of the mapping. However, here the add&nbsp;(`sa`)&nbsp;/&nbsp;replace&nbsp;(`sr`)&nbsp;/&nbsp;delete&nbsp;(`sd`) mappings all request further input *after* the mapping. vim-repeat wouldn't be able to record those inputs, so it's not really useful here.

**Comment by augustocdias** [comment]
@Daxtorim wouldn't it be just do what `ss` does?

**Comment by Daxtorim** [comment]
> wouldn't it be just do what `ss` does?

No.

When using e.g. `sa` that mapping will issue a lua function call for `surround_add()` that will then *manually* record the user's input for both the motion and the desired character. By this time, the mapping is already over, as that just issues the function call.

vim-repeat will only ever see that initial `sa`, but that by itself is not useful. vim-repeat has no way to collect the required user input afterwards for the next repeat action. Or rather, it will just replay `sa` and that will ask you to enter the previously collected input *again*. By using vim-repeat you only save a single keystroke (replacing `sa` with `.`).

`ss` works because `surround_add()` will set a global vim variable with that data. `surround_repeat()` (called by `ss`) will then use that data to construct a new call to `surround_add(arg1,character,motion)` with that data as arguments, which will then act with that info without prompting the user for input again.

You could use vim-repeat's snippet on `ss`, but that means you need to explicitly use `ss` at least once before vim-repeat lets you use `.` to repeat `ss`.

**Comment by Daxtorim** [comment]
@augustocdias Turns out, I completely misunderstood how to vim-repeat is supposed to be implemented. Or rather, I only looked at one possibility.

Easy solution: Just tell vim-repeat to repeat `ss` after every other mapping.
